### ISSUE TITLE
vt_api.py path correction

### ISSUE THREAD

**Issue by CyberTaoFlow** [perdisci/amico#10]
Greetings!  I love amico and thank you and your team.

Regarding the recent change from parsed/pe_files to parsed/captured_files.  Doing a recursive grep for pe_files returns:

amico_scripts/vt_api.py:        file_to_send = open("parsed/pe_files/%s.exe" % (md5,), "rb").read()

Other lines matched of course but were not related to the directory. I have changed the path to parsed/captured_files and have not found any ill effects.

 I think having  the extension specified is a good idea in order to avoid submitting non-public information to VT.

**Comment by perdisci** [comment]
Thank you very much for letting us know. I just push some code that should fixed the problem you reported. I will also open a separate enhancement issue related to allowing for more than .exe files to be submitted to VT, is desired. For now, the extension remains hardcoded, and therefore only .exe files are submitted.
