### ISSUE TITLE
Improve vt_api.py to allow for VT submissions other than for .exe files

### ISSUE THREAD

**Issue by perdisci** [perdisci/amico#11]
Currently, `vt_api.py` only allows to submit `.exe` files, because the file extension is hardcoded (see code below). We should allow for the extension to be specified in a config file, to make this more flexible (e.g., one may want to also automatically submit other file types (e.g., APKs, DMGs, etc.)

```
    if vt_submissions == "manual":
        file_name = "%s/%s.EXE" % (MAN_DOWNLOAD_DIR, md5)
        print "File submission to VT (manual):", file_name
        file_to_send = open(file_name, "rb").read()
    elif vt_submissions == "live":
        file_name = "parsed/captured_files/%s.exe" % (md5,)
        print "File submission to VT:", file_name
        file_to_send = open(file_name, "rb").read()
```

**Comment by CyberTaoFlow** [comment]
bump

**Comment by perdisci** [comment]
This enhancement has been made, in the experimental branch.

**Comment by perdisci** [comment]
The type of files that can be submitted to VT must be expressed in config.py.
For example:
vt_submissions_ext = ['exe','apk','dmg','jar']
