### ISSUE TITLE
PDF analysis and other ideas

### ISSUE THREAD

**Issue by CyberTaoFlow** [perdisci/amico#13]
Greetings!

I have deployed amico in a number of production networks and would like to share my observations and ideas about enhancing the functionality.  I have put some thought into how to accomplish somethings, but honestly I am only a novice developer at this point.

1. PDF feature extraction could be performed using peepdf https://github.com/jesparza/peepdf.  Peepdf is written in python so it should be fairly easy to integrate possibly via module import.

2. It would be great to get a syslog in  some post detection cases like when a virustotal verdict changes or when a malware verdict is given on a file the model classified as benign.  For example we feed the syslogs into a SIEM and give benign verdicts lower severity than malware verdicts.  When I retrain the classifier the log output tells me which dump.id's have mismatched verdicts, it would be nice to be able to get this information sooner than at training.

3. I know this is likely a tall order but support for SMTP file extraction and appropriate feature extraction (Received: header) would be great.  In enterprise environments this is usually a major vector for infection.  Some ideas for scoring/features could be seen at ( https://raw.githubusercontent.com/CyberTaoFlow/email-parser/master/www/images/flowchart.png ).  The project that is from did not take into account Received header which is very important for enterprise deployment which usually use upstream mail gateways making src-ip less than useful for classification.

4.  Running a distributed AMICO setup (multiple collection points) causes the system to frequently generate errors as it tries to upload samples to VT that are not on the local system but are in the database.  Perhaps and sensor.id column in the database would help with this (similiar to snort schema)

Thank you for all the hard work and thought you and your students / peers have put into developing this great idea into an awesome realization.

**Comment by perdisci** [comment]
Thank you for your comments. Items 1, 2, and 4 are feasible. For now we will add 2 and 4 to our TODO list, and see if we can get to 1 in the future. As for 3, the logic we use for detection would probably not adapt well to the emails scenario (the features used for our ML-based classification engine cannot be computed over SMTP communications).

**Comment by CyberTaoFlow** [comment]
Not sure if your aware of this fork that adds CM-Sketches to amico functionality.

https://github.com/umanoidTyphoon/AMICO-CM_Sketches.

Prior to finding this I had never heard of CountMin Sketches so having never seen the technique in practice I am not sure how useful it is, however the author has posted some additional reporting tools that may be worth merging into AMICO.

**Comment by perdisci** [comment]
Hello Psipher,

   yes, I'm aware of the fork. I am collaborating with the developer
on CountMin Sketches for AMICO.

Thanks for letting me know.

Regards,


Roberto
