### ISSUE TITLE
DB maintenance

### ISSUE THREAD

**Issue by CyberTaoFlow** [perdisci/amico#14]
Greetings!

I am consistently getting a score of 0.0 and was wondering if this could be due to model size and/or database content.  Are there any tips or guidance you can supply on maintaining the database?  One thing worth mentioning is that we are collecting and classifying various file-types but not submitting all of them to VT.   

As I understand it the hash's would still be checked but the file not uploaded with the following settings:

IE: 
capture_file_types = ["JAR", "APK", "MSDOC", "PDF", "ZIP", "EXE", "SWF", "DMG"]
while
vt_submissions_ext = ['exe','apk','dmg','jar','swf']

We are not submitting the document filetypes to VT because some may contain sensitive information that should not be in the public domain.   Would this cause issues with the model?  Is there a possibility that a large model would be to slow or cause issues with evaluation?

Additionally the database serves multiple instances at different sites (on different networks) however all sensors run the same config.

Thank's in advance for any guidance you can provide.

**Comment by perdisci** [comment]
Can you check if there is any recent VT result in your Amico DB where `num_av_labels > 0`?
For instance, you can run the following query:
```
amico_db=> SELECT md5, num_av_labels, query_time FROM virus_total_scans WHERE num_av_labels > 0 AND query_time > '20180701';
```

While Amico makes its own independent determination about whether a download is likely malicious or not (via the score you mentioned), it does learn from past malicious download events. So, it needs malware download examples to be able to correctly classify future malicious download events.

**Comment by CyberTaoFlow** [comment]
Yep.


               md5                | num_av_labels |         query_time         
----------------------------------+---------------+----------------------------
 6b3a51b1fee6047f72e6824f1c9f5bb2 |             1 | 2018-07-02 08:36:35.251389
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-02 23:10:52.516278
 c8942f53a7abb74552a5d1ab70c6c492 |             1 | 2018-07-05 07:09:17.276835
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-05 12:33:02.13149
 0d83a645018d9c2cd6ad9d00ff721636 |             8 | 2018-07-05 13:14:30.922002
 6b3a51b1fee6047f72e6824f1c9f5bb2 |             1 | 2018-07-06 08:45:32.680512
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-06 23:10:33.273417
 f57770534f914a74c866bff550870cc4 |             1 | 2018-07-07 12:36:57.385032
 e9cbaa44928c6c1806b038cd6b8101c5 |             2 | 2018-07-09 08:13:18.162069
 aeb6ad74958ffcda09b80eb6ef3e1ae6 |             1 | 2018-07-09 08:57:08.326671
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-09 13:54:34.917053
 aeb6ad74958ffcda09b80eb6ef3e1ae6 |             1 | 2018-07-10 10:11:50.656739
 6b3a51b1fee6047f72e6824f1c9f5bb2 |             1 | 2018-07-10 12:13:56.5195
 8dd682b6db12e986f8056cd6b9d1c458 |             1 | 2018-07-10 23:10:05.453481
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-10 23:10:16.120915
 e9cbaa44928c6c1806b038cd6b8101c5 |             2 | 2018-07-11 10:51:58.444822
 6b3a51b1fee6047f72e6824f1c9f5bb2 |             1 | 2018-07-11 12:51:57.299361
 8dd682b6db12e986f8056cd6b9d1c458 |             1 | 2018-07-12 23:10:04.242636
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-12 23:10:31.284556
 f57770534f914a74c866bff550870cc4 |             1 | 2018-07-14 23:10:08.953103
 f57770534f914a74c866bff550870cc4 |             1 | 2018-07-16 23:10:09.846691
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-16 23:10:13.640303
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-18 23:10:24.673458
 8dd682b6db12e986f8056cd6b9d1c458 |             1 | 2018-07-19 08:11:44.231184
 3af85a031404af21419f8d6d60c373e5 |             1 | 2018-07-19 10:02:28.685729
 e9cbaa44928c6c1806b038cd6b8101c5 |             1 | 2018-07-19 15:28:16.619772
 b9c756972a9eb9492efb275a342b5a4f |             1 | 2018-07-20 16:29:11.844514
 15b70451dd9be94c6a64bda76a0a597d |             1 | 2018-07-20 23:10:33.451528

**Comment by perdisci** [comment]
Are you running Amico behind a Proxy?
For instance:
```
(Scenario 1) Workstations ----Amico-----Proxy--------Internet
      
(Scenario 2) Workstations --------Proxy----Amico-----Internet                        
```
In Scenario 1, the `server` IP address seen for each download would be the proxy's IP, which would negatively influence the ability to correctly score the downloads.

If you have a Web Proxy, you would want to let Amico see the traffic between your Proxy and the Internet, to avoid the above problem.

You can also check that with a query like this:
```
SELECT server, COUNT(sha1) FROM pe_dumps GROUP BY server;
```
which should give you the distribution of the number of downloads per server IP.

**Comment by perdisci** [comment]
@CyberTaoFlow  My earlier version of the previous post did not render as intended. I corrected it, to make it clearer. I hope it helps. If you need further help, please let me know. I can suggest some other ways of looking at the data in the DB to try to figure out what is causing the constant low scores.

**Comment by CyberTaoFlow** [comment]
At one site there is a proxy in place in transparent mode as well as a firewall.  Regardless the src-ip stays that of the client.

Also we are dumping files from both the inside and outside segments in most deployments.  

server|count
 104.88.59.218   |     2
 129.237.11.204  |     1
 23.43.165.33    |     9
 74.208.170.12   |     2
 198.62.109.157  |     5
 104.28.7.38     |     1
 162.214.1.121   |     5
 216.87.186.64   |     3
 52.216.224.50   |    14
 199.223.115.54  |     1
 66.39.93.44     |     1
 207.150.218.202 |     2
 66.129.74.204   |     2
 63.131.146.150  |     1
 157.22.19.177   |    16
 195.182.62.243  |     5
 52.85.101.147   |     2
 198.154.213.140 |     3
 208.90.191.113  |    13
 104.28.27.115   |     3
 184.75.247.56   |     2
 195.195.161.211 |     2
 198.50.196.70   |     4
 146.66.68.59    |     7
 208.77.22.107   |     7
 52.216.160.227  |     2
 199.107.16.62   |     6
 67.225.191.85   |     1
 104.130.52.182  |     1
 66.228.54.138   |     4
 199.116.77.164  |     4
 192.86.102.13   |     3
 206.188.193.35  |     3
 23.61.195.115   |     8
 65.153.18.123   |     4
 143.95.98.234   |     1
 72.3.231.99     |     2
 104.130.62.224  |     3
 154.16.116.141  |     2
 52.88.157.175   |     3
 207.210.192.13  |     2
 52.85.117.12    |     2
 104.98.94.165   |     1
 195.128.8.33    |     2
 74.208.215.1    |     1
 152.11.118.182  |     1
 52.84.79.136    |     2
 208.90.189.16   |     2


Here is some  info about row counts in the DB
![image](https://user-images.githubusercontent.com/7001917/43501165-cd3fce40-9519-11e8-8b9d-2a01302770d6.png)

**Comment by CyberTaoFlow** [comment]
Just wanted to follow up and say that it appears the limitations we are placing on uploading specific file types to VT for scanning are leading to data quality issue in that alot of those files (DOC,PDF)  have null columns in the database for the ped_vts_mapping and virus_total_scans columns.

We are looking at adding functionality to use a local scanning engine or API to provide some means of providing ground truth (admittedly of potential lower quality due to limited number of engines) for these file-types.

With that said I wanted to ask if it's advisable to prune older records from the DB since they are not used for training unless we comment out the time spec in the trainer config.

**Comment by perdisci** [comment]
Files with no VT labels are still useful for extracting some of the features used by the the ML classifier. It is safe to remove them, though it may have a slight impact on classifier accuracy. I would recommend to remove unlabeled downloads that are more than N months old, for example with N=3 months. That should allow the system to still extract meaningful statistical features while removing "noise" from the database (e.g., this pruning process could be scheduled to run periodically, so you are always left with only N months of the latest unlabeled files).
