### ISSUE TITLE
file_type vs file_extension  and doubledot

### ISSUE THREAD

**Issue by CyberTaoFlow** [perdisci/amico#6]
With the experimental branch I was getting broken symlinks created in parsed/pe_files which I corrected by doing the following in start_amico.py

<         os.symlink("%s.%s" % (sha1,file_extension), md5_path)
---
>         os.symlink("%s.%s" % (sha1,file_type), md5_path)

Also with the experimental branch I was getting filenames like %hash%..pdf or %hash%..exe
I think I resolved this by removing the . from the file_extension declaration in amico_scripts/extract_file.py

138c138
<         file_extension = "exe"
---
>         file_extension = ".exe"
142c142
<         file_extension = "jar"
---
>         file_extension = ".jar"
146c146
<         file_extension = "apk"
---
>         file_extension = ".apk"
150c150
<         file_extension = "elf"
---
>         file_extension = ".elf"
154c154
<         file_extension = "dmg"
---
>         file_extension = ".dmg"
158c158
<         file_extensions = "msdoc" # generic for DOC(X), PPT(X), XLS(X), etc.
---
>         file_extensions = ".msdoc" # generic for DOC(X), PPT(X), XLS(X), etc.
162c162
<         file_extension = "rar"
---
>         file_extension = ".rar"
166c166
<         file_extension = "swf"
---
>         file_extension = ".swf"
170c170
<         file_extension = "pdf"
---
>         file_extension = ".pdf"
177c177
<         file_extenstion = "zip"
---
>         file_extenstion = ".zip"

still testing this though.

**Comment by perdisci** [comment]
Thank you for the suggestions. We are going to investigate this and apply some fixes soon.

**Comment by perdisci** [comment]
This issue has been resolved. Other related bugs in start_amico.py and extract_file.py have also been corrected.
